// Render a run as Markdown (for the vault) and as a one-file HTML board
// (published as a private Artifact). Pure: data in, strings out.

import { BUCKETS, BUCKET_LABELS } from './rollup.mjs'

const REASON_LABELS = {
  templated_city_page: 'copy-paste city page',
  out_of_area_seller: 'out-of-area seller',
  thin: 'thin page',
  outdated: 'outdated',
  off_intent: 'off-intent',
  forum_or_social: 'forum or social post',
  weak_site: 'weak site',
  directory_get_listed: 'directory (get listed)',
  strong_local_competitor: 'strong local competitor',
  strong_page: 'strong page',
  own_site: 'Triple J',
}
const INTENT_LABELS = {
  hire_installer: 'hire an installer',
  price_research: 'price research',
  buy_kit: 'buy a kit',
  info: 'information',
  navigational: 'one company',
  mixed: 'mixed',
}

export const reasonLabel = (r) => REASON_LABELS[r] ?? r ?? 'not judged'
const pct = (n, d) => (d ? `${Math.round((n / d) * 100)}%` : '–')
const usd = (n) => `$${n < 1 ? n.toFixed(3) : n.toFixed(2)}`
const md = (s) => String(s ?? '').replace(/\|/g, '\\|').replace(/\n/g, ' ')
const targetText = (t) => (t.kind === 'improve' ? `improve ${t.path}${t.label ? ` ${t.label}` : ''}` : t.label)

function whyBeatable(k) {
  const reasons = [...new Set(k.results.filter((r) => r.beatable && r.position <= 5).map((r) => reasonLabel(r.reason)))]
  return reasons.join(', ') || '–'
}

// ── Markdown ────────────────────────────────────────────────────────────────

export function renderMarkdown(run, s) {
  const out = []
  const line = (x = '') => out.push(x)
  const kwTable = (list) => {
    line('| Search | From | Intent | First beatable | Beatable in top 5 | Map pack | Work on | Why |')
    line('|---|---|---|---|---|---|---|---|')
    for (const k of list) {
      line(`| ${md(k.query)} | ${k.city} | ${INTENT_LABELS[k.intent] ?? '–'} | ${k.firstBeatable ?? '–'} | ${k.beatableTop5} | ${k.localPack.length ? 'yes' : 'no'} | ${md(targetText(k.target))} | ${md(whyBeatable(k))} |`)
    }
    line()
  }

  line(`# Keyword openings — ${run.date}`)
  line()
  line(`Generated by \`scripts/serp-steal.mjs\`. ${run.searches} searches from ${run.cities.length} cities (${run.cities.join(', ')}) via ${run.provider}, judged by \`${run.model}\`.`)
  line(`Cost: Claude judgments in this report ${usd(run.analysisCost)}. This invocation: search results ${run.serpCostLabel}, Claude ${usd(run.claudeCost)} (${run.claudeCalls} calls, ${run.cachedCalls} answered from cache).`)
  line()
  line('## Summary')
  line()
  line(`- **${s.beatableResults} of ${s.judgedResults}** judged top-10 results (${pct(s.beatableResults, s.judgedResults)}) are beatable by a strong local page.`)
  line(`- **${s.templatedResults} of ${s.results}** top-10 results are copy-paste city pages (a page at least 80% identical to the same site's page for another town).`)
  line(`- **${s.withMapPack} of ${s.keywords}** searches show a map pack above the organic results.`)
  line(`- Triple J is in the top 10 for **${s.ownRanking.length}** of ${s.keywords} searches.`)
  line(`- Buckets: ${BUCKETS.map((b) => `${BUCKET_LABELS[b]} ${s.byBucket[b].length}`).join(' · ')}.`)
  line()
  line(`## Take (${s.byBucket.take.length})`)
  line()
  line('Buyer searches with a beatable result in the top 3, or two in the top 5. Highest score first.')
  line()
  if (s.byBucket.take.length) kwTable(s.byBucket.take)
  else line('_None this run._\n')
  line(`## Content plays (${s.byBucket.content.length})`)
  line()
  if (s.byBucket.content.length) kwTable(s.byBucket.content)
  else line('_None this run._\n')
  line(`## Needs a human (${s.byBucket.human.length})`)
  line()
  line('Searchers want different things, or the judgment failed. Look at these results before writing anything.')
  line()
  for (const k of s.byBucket.human) line(`- **${k.query}** (${k.city}): ${k.rationale || 'not judged'}`)
  line()
  line(`## Triple J in the top 10 (${s.ownRanking.length})`)
  line()
  for (const k of s.ownRanking) line(`- **${k.query}** (${k.city}): position ${k.ownPosition}, ${k.ownUrl}`)
  if (!s.ownRanking.length) line('_Triple J is not in the top 10 for any search in this run._')
  line()
  line('## Map pack holders by city')
  line()
  for (const c of s.mapPack) {
    line(`- **${c.city}:** ${c.holders.slice(0, 6).map((h) => `${h.title}${h.rating ? ` (${h.rating}★, ${h.reviews ?? '?'})` : ''} ×${h.count}`).join(' · ')}`)
  }
  if (!s.mapPack.length) line('_No map packs returned._')
  line()
  line('## Directories to get listed on')
  line()
  for (const [domain, n] of s.listedIn) line(`- ${domain} (in ${n} top-10 results)`)
  if (!s.listedIn.length) line('_None._')
  line()
  line('## Who holds the top 10')
  line()
  line('| Site | Top-10 spots | Copy-paste city pages | Beatable | Type | Central Texas base |')
  line('|---|---|---|---|---|---|')
  for (const d of s.domains.slice(0, 25)) {
    line(`| ${d.domain} | ${d.appearances} | ${d.templated} | ${d.beatable} | ${d.type ?? '–'} | ${d.local ? 'yes' : 'no'} |`)
  }
  line()
  line('## Searches to try next')
  line()
  line("From Google's related searches and People also ask. Not searched in this run.")
  line()
  for (const [q, n] of s.candidates.slice(0, 40)) line(`- ${q} (${n})`)
  line()
  line('## Method and limits')
  line()
  line('- Results are mobile Google results geolocated to each city through the search API. Google itself was not scraped.')
  line('- Word counts, dates, 254 numbers, Texas ZIPs and copy-paste similarity are measured in code. Site type, depth, intent and the beatable reason are Claude judgments: spot-check them before acting.')
  line('- Beatable means a strong, specific local page could plausibly outrank the result. It does not include the map pack, which depends on the Google Business Profile.')
  line('- Search volume is not included. Most city-level searches here are too small for Google to report.')
  return out.join('\n') + '\n'
}

// ── HTML board ──────────────────────────────────────────────────────────────

const esc = (s) =>
  String(s ?? '').replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c])

function strip(k) {
  const cells = []
  for (let pos = 1; pos <= 10; pos++) {
    const r = k.results.find((x) => x.position === pos)
    const cls = !r ? 'sq none' : r.reason === 'own_site' ? 'sq own' : r.beatable ? 'sq beat' : r.reason ? 'sq hold' : 'sq none'
    const label = r ? `${pos}. ${r.domain}: ${reasonLabel(r.reason)}` : `${pos}. no result`
    cells.push(`<span class="${cls}" title="${esc(label)}"></span>`)
  }
  return `<span class="strip" aria-hidden="true">${cells.join('')}</span>`
}

function kwRows(list) {
  return list
    .map(
      (k) => `<tr>
  <td><span class="q">${esc(k.query)}</span><span class="sub">${esc(k.city)} · ${esc(INTENT_LABELS[k.intent] ?? 'not judged')}</span></td>
  <td>${strip(k)}</td>
  <td class="num">${k.firstBeatable ?? '–'}</td>
  <td class="num">${k.beatableTop5}</td>
  <td>${k.localPack.length ? 'yes' : 'no'}</td>
  <td>${esc(targetText(k.target))}</td>
  <td class="why">${esc(k.rationale)}</td>
</tr>`,
    )
    .join('\n')
}

export function renderHtml(run, s, scored) {
  const cities = [...new Set(scored.map((k) => k.city))]
  const tiles = [
    ['Searches', s.keywords, `${cities.length} cities`],
    ['Results read', s.results, `${s.judgedResults} judged`],
    ['Beatable', pct(s.beatableResults, s.judgedResults), `${s.beatableResults} results`],
    ['Copy-paste city pages', s.templatedResults, `of ${s.results} top-10 spots`],
    ['Take', s.byBucket.take.length, 'searches to go after'],
    ['Claude cost', usd(run.analysisCost), run.model],
  ]
  const wall = [...scored]
    .sort((a, b) => BUCKETS.indexOf(a.bucket) - BUCKETS.indexOf(b.bucket) || b.score - a.score)
    .map(
      (k) => `<li class="cell b-${k.bucket}" data-bucket="${k.bucket}" data-city="${esc(k.city)}">
  <span class="chip c-${k.bucket}">${esc(BUCKET_LABELS[k.bucket])}</span>
  <span class="q">${esc(k.query)}</span>
  <span class="sub">${esc(k.city)}${k.localPack.length ? ' · map pack' : ''}${k.ownPosition ? ` · Triple J #${k.ownPosition}` : ''}</span>
  ${strip(k)}
</li>`,
    )
    .join('\n')
  const reasonMax = Math.max(1, ...s.reasons.map(([, n]) => n))

  return `<title>Keyword Openings ${esc(run.month)}</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Barlow+Condensed:wght@600;700&family=Inter:wght@400;500;600&display=swap">
<style>
/* Layout: a shop-floor job board. Totals strip, then a wall of search cards,
   each carrying a ten-slot strip for Google's top 10, then the detail tables. */
:root {
  --bg: #f3f5f7;
  --panel: #ffffff;
  --ink: #15181c;
  --muted: #5a6572;
  --line: #d8dde3;
  --steel: #5f7a95;
  --amber: #f5a524;
  --amber-text: #8a5a00;
  --brand: #1e6bd6;
  --hold: #3b424b;
  --empty: #e2e6eb;
  --display: "Barlow Condensed", "Arial Narrow", system-ui, sans-serif;
  --body: "Inter", system-ui, -apple-system, "Segoe UI", sans-serif;
  --mono: ui-monospace, "SF Mono", Menlo, Consolas, monospace;
}
@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
    --bg: #0f1215; --panel: #171b20; --ink: #eef1f4; --muted: #9aa5b1; --line: #2a3038;
    --steel: #8aa3bc; --amber: #f5a524; --amber-text: #f7b547; --brand: #4d8dff; --hold: #56606b; --empty: #262c33;
    color-scheme: dark;
  }
}
:root[data-theme="dark"] {
  --bg: #0f1215; --panel: #171b20; --ink: #eef1f4; --muted: #9aa5b1; --line: #2a3038;
  --steel: #8aa3bc; --amber: #f5a524; --amber-text: #f7b547; --brand: #4d8dff; --hold: #56606b; --empty: #262c33;
  color-scheme: dark;
}
* { box-sizing: border-box; }
body { background: var(--bg); color: var(--ink); font: 14px/1.5 var(--body); }
.wrap { max-width: 1180px; margin: 0 auto; padding-inline: 16px; padding-block: 28px 56px; display: grid; gap: 32px; }
h1, h2 { font-family: var(--display); font-weight: 700; text-transform: uppercase; letter-spacing: 0.02em; text-wrap: balance; margin: 0; }
h1 { font-size: clamp(30px, 5vw, 44px); line-height: 1; }
h2 { font-size: 22px; display: flex; gap: 10px; align-items: baseline; }
h2 small { font: 500 13px var(--body); color: var(--muted); text-transform: none; letter-spacing: 0; }
.meta { color: var(--muted); margin: 6px 0 0; max-width: 75ch; }
.tiles { display: grid; grid-template-columns: repeat(auto-fit, minmax(160px, 1fr)); gap: 1px; background: var(--line); border: 1px solid var(--line); }
.tile { background: var(--panel); padding: 14px 16px; display: grid; gap: 2px; min-width: 0; }
.tile .k { font-size: 11px; letter-spacing: 0.08em; text-transform: uppercase; color: var(--muted); }
.tile .v { font: 700 34px/1.1 var(--display); font-variant-numeric: tabular-nums; }
.tile .n { font-size: 12px; color: var(--muted); overflow-wrap: anywhere; }
.legend, .filters { display: flex; flex-wrap: wrap; gap: 8px 16px; align-items: center; color: var(--muted); font-size: 12px; }
.legend span { display: inline-flex; gap: 6px; align-items: center; }
.filters button { font: 500 13px var(--body); color: var(--ink); background: var(--panel); border: 1px solid var(--line); padding: 5px 12px; border-radius: 999px; cursor: pointer; }
.filters button[aria-pressed="true"] { background: var(--ink); color: var(--bg); border-color: var(--ink); }
.filters button:focus-visible, .filters select:focus-visible { outline: 2px solid var(--brand); outline-offset: 2px; }
.filters select { font: 500 13px var(--body); color: var(--ink); background: var(--panel); border: 1px solid var(--line); padding: 5px 8px; border-radius: 6px; }
.wall { list-style: none; margin: 0; padding: 0; display: grid; grid-template-columns: repeat(auto-fill, minmax(220px, 1fr)); gap: 10px; }
.cell { background: var(--panel); border: 1px solid var(--line); border-top: 3px solid var(--line); padding: 10px 12px 12px; display: grid; gap: 4px; align-content: start; min-width: 0; }
.cell.b-take { border-top-color: var(--amber); }
.cell.b-content { border-top-color: var(--steel); }
.cell.b-held { border-top-color: var(--brand); }
.cell .q { font-weight: 600; overflow-wrap: anywhere; }
.sub { display: block; color: var(--muted); font-size: 12px; }
.chip { justify-self: start; font: 600 11px var(--body); letter-spacing: 0.06em; text-transform: uppercase; padding: 1px 7px; border-radius: 3px; border: 1px solid var(--line); color: var(--muted); }
.chip.c-take { background: var(--amber); border-color: var(--amber); color: #1c1400; }
.chip.c-content { border-color: var(--steel); color: var(--steel); }
.chip.c-held { border-color: var(--brand); color: var(--brand); }
.strip { display: inline-grid; grid-template-columns: repeat(10, 14px); gap: 3px; margin-top: 4px; }
.sq { width: 14px; height: 14px; border-radius: 2px; display: inline-block; }
.sq.beat { background: var(--amber); }
.sq.hold { background: var(--hold); }
.sq.own { background: var(--brand); }
.sq.none { background: transparent; box-shadow: inset 0 0 0 1px var(--line); }
.cols { display: grid; grid-template-columns: repeat(auto-fit, minmax(320px, 1fr)); gap: 32px; }
.cols > * { min-width: 0; }
section { display: grid; gap: 12px; min-width: 0; }
.scroll { overflow-x: auto; border: 1px solid var(--line); background: var(--panel); }
table { border-collapse: collapse; width: 100%; font-size: 13px; }
th { text-align: left; font: 600 11px var(--body); letter-spacing: 0.06em; text-transform: uppercase; color: var(--muted); padding: 8px 10px; border-bottom: 1px solid var(--line); white-space: nowrap; }
td { padding: 8px 10px; border-bottom: 1px solid var(--line); vertical-align: top; }
tr:last-child td { border-bottom: 0; }
td .q { font-weight: 600; display: block; }
td.num { font-family: var(--mono); font-variant-numeric: tabular-nums; }
.num { text-align: right; }
.why { color: var(--muted); min-width: 220px; }
.bars { display: grid; gap: 6px; }
.bar { display: grid; grid-template-columns: minmax(120px, 1fr) 2fr auto; gap: 10px; align-items: center; font-size: 13px; }
.bar i { display: block; height: 10px; background: var(--hold); border-radius: 2px; }
.bar i.beat { background: var(--amber); }
.bar b { font: 500 12px var(--mono); color: var(--muted); font-variant-numeric: tabular-nums; }
ul.plain { margin: 0; padding-left: 18px; display: grid; gap: 4px; }
.empty { color: var(--muted); font-style: italic; margin: 0; }
.note { color: var(--muted); font-size: 13px; max-width: 75ch; margin: 0; }
@media (prefers-reduced-motion: no-preference) { .filters button { transition: background 0.12s, color 0.12s; } }
</style>

<main class="wrap">
  <header>
    <h1>Keyword openings</h1>
    <p class="meta">${esc(run.date)} · ${s.keywords} Google searches from ${esc(cities.join(', '))} · results via ${esc(run.provider)} · judged by ${esc(run.model)}. A square is one of Google's top 10 results; amber means a strong local page could outrank it.</p>
  </header>

  <div class="tiles">
${tiles.map(([k, v, n]) => `    <div class="tile"><span class="k">${esc(k)}</span><span class="v">${esc(v)}</span><span class="n">${esc(n)}</span></div>`).join('\n')}
  </div>

  <section>
    <h2>The wall <small>every search, best openings first</small></h2>
    <div class="legend">
      <span><i class="sq beat"></i>beatable</span>
      <span><i class="sq hold"></i>hard to beat</span>
      <span><i class="sq own"></i>Triple J</span>
      <span><i class="sq none"></i>not judged</span>
    </div>
    <div class="filters" role="group" aria-label="Filter searches">
      <button type="button" data-filter="all" aria-pressed="true">All ${s.keywords}</button>
${BUCKETS.filter((b) => s.byBucket[b].length).map((b) => `      <button type="button" data-filter="${b}" aria-pressed="false">${esc(BUCKET_LABELS[b])} ${s.byBucket[b].length}</button>`).join('\n')}
      <label for="city-filter">City</label>
      <select id="city-filter">
        <option value="">All cities</option>
${cities.map((c) => `        <option value="${esc(c)}">${esc(c)}</option>`).join('\n')}
      </select>
    </div>
    <ul class="wall" id="wall">
${wall}
    </ul>
  </section>

  <section>
    <h2>Take <small>${s.byBucket.take.length} buyer searches with a beatable result in the top 3, or two in the top 5</small></h2>
    ${
      s.byBucket.take.length
        ? `<div class="scroll"><table>
<thead><tr><th>Search</th><th>Top 10</th><th class="num">First beatable</th><th class="num">In top 5</th><th>Map pack</th><th>Work on</th><th>Why</th></tr></thead>
<tbody>
${kwRows(s.byBucket.take)}
</tbody></table></div>`
        : '<p class="empty">None this run.</p>'
    }
  </section>

  ${
    s.byBucket.content.length
      ? `<section>
    <h2>Content plays <small>${s.byBucket.content.length} information searches held by weak pages</small></h2>
    <div class="scroll"><table>
<thead><tr><th>Search</th><th>Top 10</th><th class="num">First beatable</th><th class="num">In top 5</th><th>Map pack</th><th>Work on</th><th>Why</th></tr></thead>
<tbody>
${kwRows(s.byBucket.content)}
</tbody></table></div>
  </section>`
      : ''
  }

  <div class="cols">
    <section>
      <h2>Why results lose</h2>
      <div class="bars">
${s.reasons.map(([r, n]) => `        <div class="bar"><span>${esc(reasonLabel(r))}</span><i class="${['directory_get_listed', 'strong_local_competitor', 'strong_page', 'own_site'].includes(r) ? '' : 'beat'}" style="width:${Math.max(2, Math.round((n / reasonMax) * 100))}%"></i><b>${n}</b></div>`).join('\n')}
      </div>
    </section>
    <section>
      <h2>Needs a human <small>${s.byBucket.human.length}</small></h2>
      ${s.byBucket.human.length ? `<ul class="plain">${s.byBucket.human.map((k) => `<li><b>${esc(k.query)}</b> (${esc(k.city)}): ${esc(k.rationale || 'not judged')}</li>`).join('')}</ul>` : '<p class="empty">None.</p>'}
    </section>
  </div>

  <div class="cols">
    <section>
      <h2>Map pack by city</h2>
      ${
        s.mapPack.length
          ? `<div class="scroll"><table><thead><tr><th>City</th><th>Who holds it</th></tr></thead><tbody>${s.mapPack
              .map((c) => `<tr><td>${esc(c.city)}</td><td>${c.holders.slice(0, 5).map((h) => `${esc(h.title)}${h.rating ? ` <span class="sub" style="display:inline">${esc(h.rating)}★ · ${esc(h.reviews ?? '?')}</span>` : ''}`).join('<br>')}</td></tr>`)
              .join('')}</tbody></table></div>`
          : '<p class="empty">No map packs returned.</p>'
      }
    </section>
    <section>
      <h2>Get listed on</h2>
      ${s.listedIn.length ? `<ul class="plain">${s.listedIn.map(([d, n]) => `<li>${esc(d)} <span class="sub" style="display:inline">in ${n} top-10 results</span></li>`).join('')}</ul>` : '<p class="empty">No directories in the top 10.</p>'}
    </section>
  </div>

  <section>
    <h2>Who holds the top 10</h2>
    <div class="scroll"><table>
<thead><tr><th>Site</th><th class="num">Spots</th><th class="num">Copy-paste pages</th><th class="num">Beatable</th><th>Type</th><th>Central Texas base</th></tr></thead>
<tbody>
${s.domains.slice(0, 25).map((d) => `<tr><td>${esc(d.domain)}</td><td class="num">${d.appearances}</td><td class="num">${d.templated}</td><td class="num">${d.beatable}</td><td>${esc(d.type ?? '–')}</td><td>${d.local ? 'yes' : 'no'}</td></tr>`).join('\n')}
</tbody></table></div>
  </section>

  <section>
    <h2>Searches to try next <small>from related searches and People also ask</small></h2>
    ${s.candidates.length ? `<ul class="plain">${s.candidates.slice(0, 30).map(([q, n]) => `<li>${esc(q)} <span class="sub" style="display:inline">×${n}</span></li>`).join('')}</ul>` : '<p class="empty">None returned.</p>'}
    <p class="note">Word counts, dates, phone numbers and copy-paste similarity are measured in code. Site type, intent and the beatable reason are Claude's judgment; spot-check them before acting. Beatable does not cover the map pack, which depends on the Google Business Profile.</p>
  </section>
</main>

<script>
(function () {
  var wall = document.getElementById('wall');
  var city = document.getElementById('city-filter');
  var buttons = Array.prototype.slice.call(document.querySelectorAll('[data-filter]'));
  var bucket = 'all';
  function apply() {
    Array.prototype.forEach.call(wall.children, function (li) {
      var okB = bucket === 'all' || li.getAttribute('data-bucket') === bucket;
      var okC = !city.value || li.getAttribute('data-city') === city.value;
      li.hidden = !(okB && okC);
    });
  }
  buttons.forEach(function (b) {
    b.addEventListener('click', function () {
      bucket = b.getAttribute('data-filter');
      buttons.forEach(function (x) { x.setAttribute('aria-pressed', String(x === b)); });
      apply();
    });
  });
  city.addEventListener('change', apply);
})();
</script>
`
}
